### PR TITLE
CHG: [imx] decouple compile options for vpu & fb

### PR DESCRIPTION
**Pull request by koying**
This decouple fb support from vpu support

### CODE REVIEW

**Comment by wolfgar** [comment]
Nice...

**Comment by smallint** [comment]
Do you have issues compiling xbmc now? After running configure it is telling me that i.MX framebuffer is not available and xbmc crashes for good reason later on. All headers are there (/usr/src/linux/...)

**Comment by koying** [comment]
Strnage. Mind sharing your config.log?

**Comment by smallint** [comment]
It is telling me that linux/mxcfb.h cannot be found and that is true, under /usr/include/linux is no mxcfb.h but under /usr/src/linux/kernel/include/linux. This is actually used during compilation but not at configure stage. The log contains:

```
configure:22329: checking for i.MX framebuffer support
configure:22331: checking linux/mxcfb.h usability
configure:22331: arm-poky-linux-gnueabi-gcc  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/home/jabe/xbmc-jabe/build/tmp/sysroots/wandboard-quad -c -O2  -O2 -pipe -g -feliminate-unused-debug-types -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DNDEBUG=1 -mno-apcs-stack-check -mfpu=neon -mvectorize-with-neon-quad  conftest.c >&5
conftest.c:133:25: fatal error: linux/mxcfb.h: No such file or directory
 #include <linux/mxcfb.h>
                         ^
compilation terminated.
configure:22331: $? = 1
configure: failed program was:
```

**Comment by smallint** [comment]
I fixed the config.h and Makefile by hand to continue the work now ...

**Comment by koying** [comment]
Mmm... How come it doesn't find your `<linux/mxcfb.h>` at configure time but it finds it at compile time?

**Comment by smallint** [comment]
Good question ...

**Comment by wolfgar** [comment]
You use yocto toolchain right ?
then you might want to add : export CFLAGS=" $CFLAGS -I$OECORE_TARGET_SYSROOT/usr/src/kernel/include"
to you env before configure...

**Comment by smallint** [comment]
Thanks, I am going to try that next time I need to configure again. Now it is working with handcrafted Makefiles ;)

**Pull request merged**
