### PR TITLE
Feature/deinterlacing

### PR DESCRIPTION
**Pull request by smallint**
I tested it and it works for me for SD and 1080i channels. For some streams (e.g. Sky sample) deinterlacing is disabled with a runtime check due to performance penalties.

### CODE REVIEW

**Comment by koying** [comment]
Generally speaking, I don't watch interlaced video, but I can test with samples I have this WE.
When greenlighted for inclusion, just be sure to squash the various commits into one ;)

**Comment by wolfgar** [comment]
Very encouraging Jan : My (SD) channels look good again thanks !

In my video folder I have copied a file "Interlaced.ts" which gives strange result .
In fact it is not related to active deinterlacing (the same with IMX_DEINT_MOTION=0) but I _think_  it was ok before I merge your commit...

**Comment by smallint** [comment]
Thanks for the feedback, Stephan. I will test both versions with your sample. Can you explain a bit more detailed what "strange" means? Strange in terms of colours, cropping, smoothness? Without active deinterlacing there shouldn't be any difference compared to master but I moved some code around so maybe I broke something.

**Comment by smallint** [comment]
Your sample produces a funny colour bar at the top, right? I tested both version (master and feature/deinterlacing) and it is there in both versions. Probably it has something to do with aligning the buffers? I have here a sample that causes exactly the same but it is 1080.

**Comment by wolfgar** [comment]
Hi Jan,

Sorry for my late answer...
I really though this movie played fine before, but you are right  it is not related to this specific commit.
This comment is noise for this interlaced feature : it might be alignment/cropping issue at the end..
Regarding the default : It is not only this color bar at the top but it is also a weird vertical shadow (sorry it is not so clear I don't know how to describe this thing ;) )

**Comment by emveepee** [comment]
This link mage is from the new 3.10.30 kernel on GeekBox but I had the same issue before.  [IMG]http://i.imgur.com/YNmGHGH.jpg[/IMG] and I think it is the same colour bar issue smallint wrote about.  The top is misaligned and the colours don't seem to be aligned kind of like 3D without glass. 
Martin

**Comment by smallint** [comment]
Yep, it is. I don't know where this is coming from but it is not related to deinterlacing. I tested it with the master branch and the bar was there as well. I am on kernel 3.0.35. Can you open a new issue for that?
Jan

**Comment by smallint** [comment]
I am closing this one and create another one with squashed commits

**Pull request closed without merging**
