### PR TITLE
Improve VC1 decoding

### PR DESCRIPTION
**Pull request by wolfgar**
Improve VC1 issue reported in https://github.com/xbmc-imx6/xbmc/issues/41

### CODE REVIEW

**Comment by wolfgar** [comment]
Just to be clear regarding this PR : 
It really improves a lot the VC1 sample I use to test but after a few seconds there are still a little jerky effect. If I jump in the stream directly then the same sequence is played perfectly fine. 
There might be another issue at play for this remaining issue as this behavior suggests it is might not be  a pure decoding problem...

**Comment by koying** [comment]
Hehe... Was just about to report the same ;)
When overlaying the codec info, I see the a/v difference skyrocketting from seemingly random points while playback is flawless otherwise.
Note that I see a "Decode - Frame repeat" apparently just before. I doubt it is a coincidence ;)

**Comment by koying** [comment]
I believe this fix is purely accidental...
Your test file has no pts, so m_previousPts is always =  DVD_NOPTS_VALUE.
OTOH, the root cause might be that VPU_DEC_ONE_FRM_CONSUMED is never emitted for VC1, apparently.

**Comment by koying** [comment]
... or not. My second VC1 test file has no pts either, and always worked fine...
I'm lost.

**Comment by koying** [comment]
Yeah. This probably helps because it bypasses the fact that m_bytesToBeConsumed never drops to zero.

**Comment by wolfgar** [comment]
Your post is a little upsetting : No it is not purely accidental

First, I know VPU_DEC_ONE_FRM_CONSUMED is never emitted for vc1 (it is stated in libfslvpu) but it is not a big deal as we don't have pts.
I have profiled the duration of each ::Decode call and realized that more than 20ms were spent in this function when no additional data was available and that it did not help to produce a new picture. So the change...

There is very likely something else to understand given the remaining issue but I have  not played dice...

**Comment by koying** [comment]
Sorry, I didn't mean to upset you, of course. I thought you didn't notice :)
I really have a hard time understanding what's going on in this loop ;)

**Comment by wolfgar** [comment]
OK maybe I should have given more background...
But generally I try to follow a logical approach at least even if it is not obvious ;)

**Comment by koying** [comment]
If you allow me, it might be more obvious to not add to m_bytesToBeConsumed when we know VPU_DEC_ONE_FRM_CONSUMED is not emitted, wouldn't it?
I don't know if it is possible, but if we have VC1 + pts, the fix wouldn't work.

**Comment by wolfgar** [comment]
That is very true : I will update the patch that way in a few minutes...

**Comment by wolfgar** [comment]
This update increases m_bytesToBeConsumed only when VPU_DEC_ONE_FRM_CONSUMED can be generated.
For completeness, this is currently the case for the following codecs : 
VPU_V_DIVX4, VPU_V_DIVX56, VPU_V_XVID, VPU_V_MPEG4, VPU_V_AVC
according to libfslvpuwrap...

**Comment by koying** [comment]
For test, I've tried with my old "pts queue" system, which used dts if we had no pts and it solves the issue of the test file going crazy at some point (Currently, I see that the video is actually going too fast ;) ).
There are frame dropppings, but the playback correctly recovers.

As I hinted, passing no pts nor dts do not seem fool-proofed inside XBMC...

**Comment by wolfgar** [comment]
First, is the updated patch OK for you ?

Then I don't perfectly understand your report : does the dts queue enable to have correct playback or not ? With which implementation can you see the video that goes "too fast" ?

For the pts/dts implementation, note that I took the time to write #32 so that we can have constructive exchanges regarding the best implementation but you have not yet joined the discussion...
I think that the current implementation is  very robust when pts are present and VPU_DEC_ONE_FRM_CONSUMED are emitted (and it is for real :I have stressed it a lot with livetv and bad signal)  but I clearly have doubts for the no pts and/or no VPU_DEC_ONE_FRM_CONSUMED case.
My mind is the same as what I [wrote](https://github.com/xbmc-imx6/xbmc/pull/8#issuecomment-35965865) 20 days ago : 
"
can we simply let the player guess the pts given frame rate (which seems to be ok with your short sample.) or do we really have to implement a queue to deal with dts from AVI ?
[...]
For now, I sincerely don't know whether there might be an advantage 
"
If this case is an obvious proof that the no pts case has to be addressed differently than letting the player do its best given the fps then let's discuss how to improve the implementation...
If switching to the queue only changes the issue with this file then it means we still have to understand the real root case for bad playback of this specific file.
But we can still challenge and improve the pts/dts stuff...

**Comment by koying** [comment]
Arf. Not discussing the pts system, here. You have your opinion, I have mine, and I doubt either of us will change its mind.

Just saying that the remaining issue with the VC1 file is due to the fact that we are passing no pts to XBMC, and that due to this, XBMC is loosing it at some point. 
As I suspected this, I only used my old PR for confirmation, because I just don't see how to pass the dts with your system, if VPU_DEC_ONE_FRM_CONSUMED is not called.

Bottom-line: Passing no pts back to XBMC is a big no-no. Even if you don't trust me on this, be prepared to have the PR refused for that by the XBMC reviewers. I know this from experience.

**Comment by koying** [comment]
P.S. If I was not clear enough, playback of your VC1 file is flawless with the PTS queue system, so is achievable.

**Comment by koying** [comment]
P.P.S To answer your 1st question, yes, the patch is working in that it produces the same results as the original one.

**Comment by wolfgar** [comment]
Of course it is related to pts as the current pts handling has the drawback of passing NO_PTS in some  cases.
I think I have proven to be open and to always try to find the best option so I can hardly understand your remark " You have your opinion, I have mine, and I doubt either of us will change its mind" ...
Moreover the question for the patch update was to confirm that this change was better and in line with your remark and not only to confirm it behaves the same...

**Comment by koying** [comment]
Re the patch update, it would be nice to add some comments, as the link between VPU_DEC_CAP_FRAMESIZE and VPU_DEC_ONE_FRM_CONSUMED not being generated is still not obvious.

Re the PTS system, best is probably that you try to find a workaround for when VPU_DEC_ONE_FRM_CONSUMED is not generated (you master the system, I don't known if someone else can help you, there). If that's not possible, we can resume the brainstorming.

**Comment by wolfgar** [comment]
OK, for the patch, I have just added a comment and pushed the new version
If you are OK with the current state you can merge it tomorrow.

Then we have to discuss about no pts/ no VPU_DEC_ONE_FRM_CONSUMED  in #32 for sure...

**Pull request merged**
