### PR TITLE
FIX: [imx] drop decoder frames which are returned with flag VPU_DEC_OUTP...

### PR DESCRIPTION
**Pull request by smallint**
...UT_MOSAIC_DIS set

### CODE REVIEW

**Comment by wolfgar** [comment]
Apart from minor previous remark, the VPU_DEC_OUTPUT_MOSAIC case appears nice to me

**Comment by koying** [comment]
Yep. This might be the cause of the "mosaic" + desync effect I mentioned earlier.

**Comment by smallint** [comment]
If we merge this branch we must not forget to pop a pts from the queue in that case to not break the chgpts branch. I am also quite sure that a pts must be popped when VPU_DEC_OUTPUT_DROPPED is returned. Currently we disabled dropping frames at decoder side but the case is handled -> consistency.

**Comment by wolfgar** [comment]
Yes in case of queue we will have to add pop where the tsreceive were called (and in this new mosaic case)
Of course it will be a blind action as we will not know for sure which pts has to be dropped  in these error cases...

**Comment by wolfgar** [comment]
As an additional question : Do you have streams where the branch is taken ?
Because I conceptually agree with the change but I added a log to track when we take this branch and I have no trace (even on livetv stream)

**Comment by smallint** [comment]
No, not a single one. But after Chris mentioned the mosaic effect in one of his videos I just recalled what I read before about this state and added it to comply with "official" implementations and libraries. Actually I have never seen a log so far.

**Comment by wolfgar** [comment]
At last I managed to have a few mosaic cases with a very bad hd channel.
Time to merge...

**Pull request merged**
