### PR TITLE
FIX: [imx] Do not force resolution if the same as current

### PR DESCRIPTION
**Pull request by koying**
This seems to solve the "transparent" screen effect for me

### CODE REVIEW

**Comment by wolfgar** [comment]
This issue is too rare for me so I cannot confirm for sure it solves the issue but it cannot hurt so good to merge this we as soon as the 24h delay is over
can we close the question #15 ?

**Comment by smallint** [comment]
I have now another funny but correlated effect. When sometimes starting a stream in fullscreen which needs causes a mode switch it plays in background. The xbmc gui is still visible but static. I can stop the stream and navigate (I hear the sound) but nothing happens on the active framebuffer. Looks like xbmc is running now on a different one.

**Comment by wolfgar** [comment]
OK it might mean the real root cause is still at play here...
Very difficult to investigate because it happens very very rarely in my environment. Are you aware of a specific configuration  that may make this issue more likely to occur ?

**Comment by smallint** [comment]
My config is (was: I disabled it now) set to change resolution "Always" with a delay of 1.5s. My screen is set to 50Hz and playing Interlaces.ts which switches to 60Hz either causes a wrong switch at start or after stop. This happens almost always with Interlaced.ts.

**Comment by smallint** [comment]
I loose vsync after I switched off my display and switched it on again (usually after a day, haven't checked a lower time span). Restarting xbmc helps. I have this PR applied. Blanking/unblanking does not help.

**Comment by wolfgar** [comment]
@smallint : I cannot reproduce your issue 
I merge this PR  which is in standby for a long time ...

**Pull request merged**
