### PR TITLE
detect imx device on all platform using file /sys/class/graphics/fb0/fsl...

### PR DESCRIPTION
**Pull request by tomlohave**
..._disp_dev_property

### CODE REVIEW

**Comment by CrawX** [comment]
+1 from me, see my comment in #51.

**Comment by tomlohave** [comment]
Done, as you suggested.
Tested on cuboxi.

**Comment by wolfgar** [comment]
Nice, it was style only but as the implicit cast was already done I found the verbose form useless ...
I will merge tomorrow if no additional remark is posted

**Pull request merged**
