### PR TITLE
Bitsream conv fix part#2

### PR DESCRIPTION
**Pull request by wolfgar**
Second part of the patch for issue #65

### CODE REVIEW

**Comment by wolfgar** [comment]
Breaks some files : Do not merge...

**Comment by wolfgar** [comment]
Last variant of the fix which seems all good ...
Thank you very much @koying

**Comment by koying** [comment]
Note that we might end up with a conflict if my patch is not accepted in XBMC...

**Comment by wolfgar** [comment]
I understand but what is the best immediate action for the master of this repository ?
This fix appears to improve our experience without drawback (at least at the extend of our current testing) as it allows to play properly some streams that had artifacts previously...
What I propose, if you agree, is the following : let's merge it right now in our master and maybe delay the merge in master-pr (which will be the real problematic struff subject to upstream merge) by the time the initial PR makes its way.
If it helps I can post in this original PR but I would like to avoid conflict. Whether we manage to find a global agreement about this stuff (at first sight, it should be possible as the initial FFMPEG fix shows that there is a generic concern at play) whether it is a no go and I will try to investigate another way to solve it  (Properly configured, the imx VPU might be able to deal with the original stream without the bitstream conversion and that could be a last resort way to deal with the issue"locally" to imx6 related stuff...)

**Comment by koying** [comment]
Sure, no problem to merge it into master.
Just something to keep in mind for master-pr...

The problem is real and global. I'm just not an ffmpeg guru, so the final solution might be different ;)

**Comment by wolfgar** [comment]
No problem, I am not an expert of this stuff neither but with my global understanding of this annex B conversion stuff, your fix seems really logical to me...
I have testified in the xbmc PR 
I merge this PR right now even if I opened it as the fix is from you and we shared our agreement regarding merging it...

**Pull request merged**
