### PR TITLE
[imx] A VPU_DEC_FLUSH should amount to a Reset()

### PR DESCRIPTION
**Pull request by koying**
Self-explanatory ;)

### CODE REVIEW

**Comment by wolfgar** [comment]
I can't really try it as I don't know how to trigger this event but conceptually it looks perfectly fine

**Comment by smallint** [comment]
Same here. I have never seen the flush event. Semantically flush and reset are different things to my understanding but I must admit that I don' really know what a vpu flush is about. With reset we will throw away frames/pictures.

**Comment by koying** [comment]
Never had the occurrence myself either (that I know of). 
Just that i guess that if we do a flush on the vpu, we have to do the same housekeeping as we do when a reset is done.

**Comment by wolfgar** [comment]
I think the same conceptually
Maybe reality will disagree at some stage ;)
For now I merge it

**Pull request merged**
